#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	
	[0] = LAYOUT_ortho_3x10(
	KC_PPLS,  KC_P1,  KC_P4,  KC_P7,  KC_PSLS,  KC_NLCK,  KC_F13,  RGB_TOG,  KC_MPRV,  KC_VOLD, 
	KC_P0,	  KC_P2,  KC_P5,  KC_P8,  KC_PAST,  KC_F16,   KC_F14,  RGB_MOD,  KC_MNXT,  KC_VOLU, 
	KC_PENT,  KC_P3,  KC_P6,  KC_P9,  KC_PMNS,  KC_F17,   KC_F15,  RGB_RMOD, KC_MPLY,  KC_MUTE
	)
};

